ALTER TABLE alugueis
    ADD COLUMN acrescimo DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    ADD COLUMN desconto DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    ADD COLUMN valor_frete DECIMAL(10, 2) NOT NULL DEFAULT 0.00;