# =======================================
# CONFIGURAÇÃO DO BANCO DE DADOS (MySQL)
# =======================================

# 1. Onde está o banco?
# Estamos dizendo que ele está nesta máquina (localhost), na porta 3306,
# e que o banco de dados que queremos usar se chama "festagestor_db".
spring.datasource.url=jdbc:mysql://localhost:3306/festagestor_db

# 2. Quem está acessando?
# Use o usuário "root" (padrão) e a senha que você criou durante a instalação.
spring.datasource.username=root
spring.datasource.password=Leticia@2110

# =======================================
# CONFIGURAÇÃO DO JPA (A "MÁGICA")
# =======================================

# 3. O que o JPA deve fazer quando o sistema ligar?
# "update" = Olhe minhas classes @Entity e atualize o banco de dados.
# Se as tabelas não existirem, crie-as. Se existirem, não faça nada.
spring.jpa.hibernate.ddl-auto=update

# 4. O que eu quero ver no console?
# "true" = Mostre-me no console todo comando SQL que você
# estiver executando por trás dos panos. (Ótimo para aprender!)
spring.jpa.show-sql=true

# Opcional: Deixa o SQL mostrado no console mais bonito e legível
spring.jpa.properties.hibernate.format_sql=true